name: Check for schedule updates

on:
  schedule:
    - cron:  '* * * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Cache Selenium webdriver
      uses: actions/cache@v4
      with:
        path: ~/.cache/selenium
        key: ${{ runner.os }}-selenium-${{ hashFiles('~/.cache/selenium') }}
        restore-keys: |
          ${{ runner.os }}-selenium-

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Log files before run
      shell: bash
      run: |
        pwd
        ls -las .
        ls -las .days
        ls -las ~/.cache/selenium/ || echo "not found: ~/.cache/selenium/"
    - name: Run check
      run: ./gradlew run
    - name: Log results
      shell: bash
      run: |
        pwd
        ls -las .
        ls -las .days
        ls -las ~/.cache/selenium/ || echo "not found: ~/.cache/selenium/"
    - name: Commit update data
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        file_pattern: '.days/*.json'
        commit_message: "Update schedule"
        skip_fetch: true
        skip_checkout: true
