name: Check for schedule updates

on:
  schedule:
    - cron:  '* * * * *'
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Run check
      uses: gradle/gradle-build-action@v3
      with:
        arguments: run
    - name: Log results
      run: |
        pwd
        ls -las .
        ls -las .days
        ls -las ~/.cache/selenium/
      shell: bash
