name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Run tests
      run: ./gradlew check
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        retention-days: 7
        path: |
          **/build/reports
          **/build/test-results
